"""empty message

Revision ID: 7e93ec9f2b26
Revises: 
Create Date: 2017-01-22 23:30:34.799315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e93ec9f2b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('names', sa.String(length=128), nullable=True),
    sa.Column('reg_no', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('what', sa.String(length=300), nullable=False),
    sa.Column('when', sa.String(length=300), nullable=False),
    sa.Column('where', sa.String(length=300), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['docs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('docs')
    # ### end Alembic commands ###
